version: "3.9"
services:
  app:
    environment:
      model: "test"
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    volumes:
      - ./:/workspace/kloser
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    command: bash -c "cd /workspace/kloser && uvicorn src.app:app --host 0.0.0.0 --port 80 --workers 1"